version: "3.8"

services:
    web:
        build:
            context: .
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - db
            - phpmyadmin
            - node
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nineonelabs
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root

    node:
        image: node:22.15
        volumes:
            - ./:/app
        working_dir: /app
volumes:
    db_data:
