-- 스튜디오 티나 뉴스 데이터 (20개)
-- board_no: 25 (뉴스)
-- thumb_image: 68ecacca8a4050.63791605.png (고정)

-- 기존 게시물 sort_no 밀기
UPDATE `nb_board` SET `sort_no` = `sort_no` + 20 WHERE `sitekey` = 'STTINA' AND `board_no` = 25;

-- 1. AI 영상 제작 기술로 한국콘텐츠진흥원 선정
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(150, 'STTINA', 25, -1, 0, 0, '스튜디오 티나, AI 기반 영상 제작 기술로 한국콘텐츠진흥원 선정', '<div><p>스튜디오 티나가 한국콘텐츠진흥원이 주관하는 2025년 \'AI 영상 콘텐츠 제작지원\' 사업 단편 부문에 선정되었습니다.</p><p>이번 프로젝트에서는 영화 \'택시운전사\', \'고지전\', \'의형제\'의 장훈 감독이 연출과 각본에 참여하는 단편영화 &lt;아들니스&gt;를 제작하며, 스튜디오 티나는 AI 기반 영상 제작 기술을 총괄합니다.</p><p>스튜디오 티나의 AI 풀파이프라인 기술은 기존 영상 제작 과정을 혁신적으로 개선하여 제작 시간을 단축하고 완성도 높은 결과물을 만들어내는 것으로 평가받고 있습니다.</p></div>', '2025-10-13 16:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'studio-tina-selected-kocca-ai-content-production-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1);

-- 2. 서울예술대학교 아트프로젝트 선정
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(151, 'STTINA', 25, -1, 0, 0, '단편영화 \'사랑의 아포칼립스\' 서울예술대학교 아트프로젝트 선정', '<div><p>스튜디오 티나가 제작에 참여한 단편영화 &lt;사랑의 아포칼립스&gt;가 서울예술대학교 2025년 미디어컨텐츠산업 아트프로젝트에 선정되었습니다.</p><p>영화 \'극한직업\'의 문충일 작가가 연출과 각본에 참여한 이번 작품은 AI 영상 기술과 전통적인 영화 제작 기법을 조화롭게 결합한 것이 특징입니다.</p><p>스튜디오 티나는 AI 기반 배경 생성과 후반 작업을 담당하며 완성도 높은 영상미를 구현했습니다.</p></div>', '2025-10-10 14:30:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'love-apocalypse-seoul-art-university-project-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2);

-- 3. 숏폼드라마 자매전쟁 제작
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(152, 'STTINA', 25, -1, 0, 0, '숏폼드라마 \'자매전쟁\' 기술총괄 참여', '<div><p>스튜디오 티나가 숏폼드라마 &lt;자매전쟁&gt; 제작에 기술총괄로 참여합니다.</p><p>이번 프로젝트에서는 AI 기반 편집 자동화 시스템과 실시간 렌더링 기술을 활용하여 빠른 제작 속도와 높은 완성도를 동시에 달성했습니다.</p><p>숏폼 콘텐츠에 최적화된 스튜디오 티나의 기술력이 새로운 콘텐츠 제작 방식을 제시할 것으로 기대됩니다.</p></div>', '2025-09-28 11:20:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'short-drama-sisters-war-technical-director-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 3);

-- 4. Netflix 오리지널 VFX 파트너십
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(153, 'STTINA', 25, -1, 0, 0, 'Netflix 오리지널 시리즈 VFX 파트너십 체결', '<div><p>스튜디오 티나가 글로벌 OTT 플랫폼 Netflix와 VFX 파트너십을 체결했습니다.</p><p>이번 협약을 통해 스튜디오 티나는 Netflix 오리지널 한국 시리즈의 시각효과 제작에 참여하게 되며, AI 기반 VFX 기술을 활용한 혁신적인 영상미를 선보일 예정입니다.</p><p>스튜디오 티나 관계자는 "글로벌 플랫폼과의 협력을 통해 K-콘텐츠의 기술적 경쟁력을 한층 강화할 수 있게 되었다"고 밝혔습니다.</p></div>', '2025-09-15 15:40:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'netflix-original-series-vfx-partnership-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 4);

-- 5. 백상예술대상 기술상 수상
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(154, 'STTINA', 25, -1, 0, 0, '제59회 백상예술대상 기술상 수상', '<div><p>스튜디오 티나가 제59회 백상예술대상 기술상을 수상했습니다.</p><p>영화 &lt;더 문&gt;의 AI 기반 VFX 제작에 기여한 공로를 인정받아 이번 수상의 영예를 안았습니다.</p><p>심사위원단은 "AI 기술과 전통적인 VFX 기법의 조화로운 결합이 한국 영상 산업의 기술적 발전을 이끌었다"고 평가했습니다.</p><p>스튜디오 티나는 앞으로도 기술 혁신을 통해 영상 산업 발전에 기여하겠다는 포부를 밝혔습니다.</p></div>', '2025-08-20 18:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'baeksang-arts-awards-technical-award-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 5);

-- 6. AI 영상 제작 툴킷 v2.0 출시
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(155, 'STTINA', 25, -1, 0, 0, 'AI 영상 제작 툴킷 v2.0 정식 출시', '<div><p>스튜디오 티나가 자체 개발한 AI 영상 제작 툴킷 v2.0을 정식 출시했습니다.</p><p>이번 버전은 실시간 렌더링 속도가 기존 대비 300% 향상되었으며, 자동 편집 기능이 대폭 강화되었습니다.</p><p>특히 딥러닝 기반의 장면 인식 기술을 적용하여 편집자의 작업 효율을 획기적으로 개선했습니다.</p><p>업계 관계자들은 "중소 제작사도 고품질 영상을 빠르게 제작할 수 있는 환경이 조성되었다"며 긍정적인 반응을 보이고 있습니다.</p></div>', '2025-07-12 10:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'ai-video-production-toolkit-v2-release-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 6);

-- 7. 강남 사옥 이전
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(156, 'STTINA', 25, -1, 0, 0, '스튜디오 티나, 강남 신사옥으로 이전', '<div><p>스튜디오 티나가 강남구 테헤란로에 위치한 신사옥으로 이전했습니다.</p><p>500평 규모의 새 사옥에는 최신 AI 렌더링 장비와 프로덕션 스튜디오가 구축되어 대규모 프로젝트 수행이 가능해졌습니다.</p><p>특히 4K/8K 영상 제작을 위한 전용 렌더팜과 실시간 협업이 가능한 스마트 워크스페이스를 갖추었습니다.</p><p>회사 측은 "확장된 공간과 최신 설비를 바탕으로 더 많은 혁신적인 프로젝트를 진행할 계획"이라고 밝혔습니다.</p></div>', '2025-06-05 13:30:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'studio-tina-gangnam-new-office-relocation-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 7);

-- 8. tvN 드라마 시간의 저편 AI 배경 제작
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(157, 'STTINA', 25, -1, 0, 0, 'tvN 드라마 \'시간의 저편\' AI 배경 제작 참여', '<div><p>스튜디오 티나가 tvN 드라마 &lt;시간의 저편&gt;의 AI 배경 제작에 참여했습니다.</p><p>SF 장르 특성상 현실에 존재하지 않는 미래 도시와 우주 공간을 구현해야 했던 이번 프로젝트에서 AI 기반 배경 생성 기술이 큰 역할을 했습니다.</p><p>제작진은 "촬영 비용을 30% 절감하면서도 시각적 완성도를 높일 수 있었다"며 만족감을 표했습니다.</p></div>', '2025-05-18 16:20:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'tvn-drama-beyond-time-ai-background-production-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8);

-- 9. 부산국제영화제 VR 콘텐츠 제작
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(158, 'STTINA', 25, -1, 0, 0, '부산국제영화제 VR 콘텐츠 제작 참여', '<div><p>스튜디오 티나가 부산국제영화제 VR 시네마 부문 공식 초청작 제작에 참여했습니다.</p><p>AI 기반 360도 영상 생성 기술과 실시간 렌더링을 활용하여 몰입감 높은 VR 콘텐츠를 구현했습니다.</p><p>관람객들은 "기존 VR 콘텐츠와는 차원이 다른 시각적 경험"이라며 높은 평가를 내렸습니다.</p><p>스튜디오 티나는 이번 성과를 바탕으로 VR/AR 콘텐츠 제작 영역을 확대할 계획입니다.</p></div>', '2025-04-22 14:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'busan-film-festival-vr-content-production-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 9);

-- 10. 문화체육관광부 우수 콘텐츠 기업 선정
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(159, 'STTINA', 25, -1, 0, 0, '문화체육관광부 우수 콘텐츠 기업 선정', '<div><p>스튜디오 티나가 문화체육관광부가 선정하는 2025년 우수 콘텐츠 기업에 이름을 올렸습니다.</p><p>AI 기술을 활용한 혁신적인 영상 제작 방식과 콘텐츠 산업 발전에 기여한 공로를 인정받았습니다.</p><p>선정 기업에는 R&D 지원금과 해외 진출 지원 등 다양한 혜택이 제공됩니다.</p></div>', '2025-03-10 11:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'ministry-culture-sports-tourism-excellent-company-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 10);

-- 11. AI 전문 인력 30명 채용
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(160, 'STTINA', 25, -1, 0, 0, '영상 AI 전문 인력 30명 추가 채용', '<div><p>스튜디오 티나가 사업 확장에 따라 영상 AI 전문 인력 30명을 추가로 채용합니다.</p><p>AI 엔지니어, 딥러닝 연구원, VFX 아티스트 등 다양한 직군에서 인재를 모집하며, 업계 최고 수준의 복지와 연봉을 제시할 예정입니다.</p><p>특히 신입 개발자를 위한 체계적인 교육 프로그램과 멘토링 시스템을 운영하여 AI 영상 전문가 양성에도 힘쓸 계획입니다.</p></div>', '2025-02-14 09:30:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'ai-video-specialist-recruitment-30-positions-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 11);

-- 12. AI 모션 캡처 시스템 구축
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(161, 'STTINA', 25, -1, 0, 0, 'AI 모션 캡처 시스템 구축 완료', '<div><p>스튜디오 티나가 최신 AI 모션 캡처 시스템 구축을 완료했습니다.</p><p>기존 모션 캡처 장비와 달리 별도의 마커 없이도 정확한 동작 추적이 가능하며, 실시간으로 3D 캐릭터에 적용할 수 있습니다.</p><p>이 시스템은 메타휴먼 제작과 가상 프로덕션에 활용되어 제작 효율을 크게 높일 것으로 기대됩니다.</p></div>', '2025-01-28 15:45:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'ai-motion-capture-system-completion-2025', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 12);

-- 13. 서울대학교 AI 연구소 MOU
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(162, 'STTINA', 25, -1, 0, 0, '서울대학교 AI 연구소와 산학협력 MOU 체결', '<div><p>스튜디오 티나가 서울대학교 AI 연구소와 산학협력 업무협약을 체결했습니다.</p><p>양측은 AI 영상 기술 공동 연구, 인재 양성, 기술 이전 등에서 협력하기로 합의했습니다.</p><p>특히 차세대 영상 생성 AI 모델 개발과 실시간 렌더링 기술 고도화를 위한 공동 연구가 진행될 예정입니다.</p><p>연구 성과는 학술 논문 발표와 함께 실제 콘텐츠 제작에도 적용될 계획입니다.</p></div>', '2024-12-15 10:20:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'seoul-national-university-ai-lab-mou-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 13);

-- 14. 중소벤처기업부 기술혁신대상 수상
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(163, 'STTINA', 25, -1, 0, 0, '중소벤처기업부 기술혁신대상 수상', '<div><p>스튜디오 티나가 중소벤처기업부가 주관하는 2024년 기술혁신대상을 수상했습니다.</p><p>AI 기반 영상 편집 자동화 시스템 개발로 콘텐츠 제작 산업의 혁신을 이끈 공로를 인정받았습니다.</p><p>심사위원단은 "중소 규모 제작사도 고품질 콘텐츠를 효율적으로 만들 수 있는 생태계를 조성했다"며 높이 평가했습니다.</p></div>', '2024-11-08 17:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'mss-technology-innovation-award-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 14);

-- 15. 일본 도쿄 지사 설립
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(164, 'STTINA', 25, -1, 0, 0, '일본 도쿄 지사 설립으로 글로벌 확장', '<div><p>스튜디오 티나가 일본 도쿄에 해외 첫 지사를 설립했습니다.</p><p>일본 애니메이션 및 영상 제작 시장 진출을 목표로 현지 파트너사들과 협력 체계를 구축할 예정입니다.</p><p>도쿄 지사는 일본 시장 특화 콘텐츠 제작 지원과 함께 현지 기술 인력 채용도 진행할 계획입니다.</p><p>회사 측은 "2026년까지 미주 및 유럽 시장에도 진출할 것"이라며 글로벌 확장 계획을 밝혔습니다.</p></div>', '2024-10-20 13:15:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'tokyo-branch-office-global-expansion-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 15);

-- 16. CJ ENM 전략적 파트너십
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(165, 'STTINA', 25, -1, 0, 0, 'CJ ENM과 AI 콘텐츠 제작 전략적 파트너십 체결', '<div><p>스튜디오 티나가 국내 최대 콘텐츠 기업 CJ ENM과 전략적 파트너십을 체결했습니다.</p><p>양사는 AI 기술을 활용한 드라마, 예능, 영화 등 다양한 장르의 콘텐츠 공동 제작에 협력하기로 했습니다.</p><p>특히 CJ ENM의 콘텐츠 기획력과 스튜디오 티나의 AI 기술력이 결합하여 글로벌 시장을 겨냥한 차별화된 콘텐츠를 선보일 예정입니다.</p></div>', '2024-09-05 11:40:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'cj-enm-strategic-partnership-ai-content-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16);

-- 17. 티나TV 플랫폼 런칭
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(166, 'STTINA', 25, -1, 0, 0, '숏폼 콘텐츠 플랫폼 \'티나TV\' 정식 런칭', '<div><p>스튜디오 티나가 자체 숏폼 콘텐츠 플랫폼 \'티나TV\'를 정식 런칭했습니다.</p><p>AI 기반 추천 알고리즘과 크리에이터 지원 시스템을 갖춘 티나TV는 누구나 쉽게 고품질 숏폼 콘텐츠를 제작하고 공유할 수 있는 환경을 제공합니다.</p><p>특히 AI 편집 도구를 무료로 제공하여 일반 사용자도 전문가 수준의 영상을 만들 수 있습니다.</p><p>베타 테스트 기간 동안 10만 명 이상의 크리에이터가 등록하며 뜨거운 관심을 받았습니다.</p></div>', '2024-07-18 14:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'tina-tv-short-form-platform-launch-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 17);

-- 18. AI 배우 생성 기술 개발 착수
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(167, 'STTINA', 25, -1, 0, 0, 'AI 가상 배우 생성 기술 개발 착수', '<div><p>스튜디오 티나가 차세대 AI 가상 배우 생성 기술 개발에 착수했습니다.</p><p>실제 배우의 동작과 표정을 학습하여 자연스러운 연기가 가능한 디지털 휴먼을 만드는 것이 목표입니다.</p><p>이 기술이 상용화되면 촬영 일정 조율, 배우 섭외 등의 어려움을 해결하고 제작 비용도 크게 절감할 수 있을 것으로 기대됩니다.</p><p>2026년 상반기 프로토타입 공개를 목표로 연구 개발을 진행 중입니다.</p></div>', '2024-05-30 16:30:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'ai-virtual-actor-technology-development-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 18);

-- 19. 시리즈 B 투자 유치
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(168, 'STTINA', 25, -1, 0, 0, '시리즈 B 투자 유치 100억원 달성', '<div><p>스튜디오 티나가 시리즈 B 라운드에서 100억원 규모의 투자를 유치했습니다.</p><p>국내 주요 벤처캐피털과 전략적 투자자들이 참여한 이번 투자는 AI 영상 기술 R&D 강화와 글로벌 시장 진출에 사용될 예정입니다.</p><p>투자사 관계자는 "AI 기반 콘텐츠 제작 시장의 폭발적 성장이 예상되는 가운데 스튜디오 티나의 기술력과 실행력을 높이 평가했다"고 밝혔습니다.</p><p>회사 측은 이번 투자를 바탕으로 2025년 매출 500억원 달성을 목표로 하고 있습니다.</p></div>', '2024-04-12 10:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'series-b-investment-10-billion-won-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 19);

-- 20. KAIST AI 대학원 공동 연구
INSERT INTO `nb_board` (`no`, `sitekey`, `board_no`, `user_no`, `category_no`, `comment_cnt`, `title`, `contents`, `regdate`, `read_cnt`, `thumb_image`, `is_admin_writed`, `is_notice`, `is_secret`, `secret_pwd`, `write_name`, `isFile`, `file_attach_1`, `file_attach_origin_1`, `file_attach_2`, `file_attach_origin_2`, `file_attach_3`, `file_attach_origin_3`, `file_attach_4`, `file_attach_origin_4`, `file_attach_5`, `file_attach_origin_5`, `is_admin_comment_yn`, `direct_url`, `extra1`, `extra2`, `extra3`, `extra4`, `extra5`, `extra6`, `extra7`, `extra8`, `extra9`, `extra10`, `extra11`, `extra12`, `extra13`, `extra14`, `extra15`, `extra16`, `extra17`, `extra18`, `extra19`, `extra20`, `extra21`, `extra22`, `extra23`, `extra24`, `extra25`, `extra26`, `extra27`, `extra28`, `extra29`, `extra30`, `sort_no`) VALUES
(169, 'STTINA', 25, -1, 0, 0, 'KAIST AI 대학원과 공동 연구 프로젝트 시작', '<div><p>스튜디오 티나가 KAIST AI 대학원과 공동 연구 프로젝트를 시작했습니다.</p><p>차세대 영상 생성 AI 모델 개발을 주제로 3년간 진행되는 이번 연구는 정부 R&D 과제로도 선정되었습니다.</p><p>연구팀은 텍스트나 간단한 스케치만으로 영화급 퀄리티의 영상을 생성할 수 있는 AI 모델 개발을 목표로 하고 있습니다.</p><p>연구 성과는 국제 학술지 발표는 물론 실제 콘텐츠 제작 현장에도 즉시 적용될 예정입니다.</p></div>', '2024-02-25 09:00:00', 0, '68ecacca8a4050.63791605.png', 'N', 'N', 'N', NULL, '관리자', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'kaist-ai-graduate-school-joint-research-2024', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 20);

